<a href="https://colab.research.google.com/github/rishisaini1223/Machine-Learning/blob/main/LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#workflow of machine learning
# Data Ingestion ---> Data Cleaning and Preprocessing  ---> Select Best ML MOdel  according to data--->
# Model Trainig --> Model Prediction  --> model performance evaluation.

In [ ]:
# Types od ML Models :::
# 1. Supervised ML models ---> in this, we will train our labelled data.
# 2. UnSupervised ML models ---> in this, we will train our unlavelled data.

In [ ]:
# 1. Supervised ML models

In [ ]:
# If our target data is :::
# 1. Numerical --> LinearRegression , D.T.Regressor, R.F.Regressor
# 2. Categorical ---> LogisticRegression, D.T.Classifier, R.F.Classifier, Naive bayes, SVM, KNN

In [ ]:
#1. LinearRegression MOdel :::

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("/content/insurance - insurance.csv")
df.head(2)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lb = LabelEncoder()

In [ ]:
df['region'] = lb.fit_transform(df['region'])
df["sex"] = lb.fit_transform(df['sex'])
df['smoker'] = lb.fit_transform(df['smoker'])

In [ ]:
x = df.drop(columns= ['charges'])
y = df['charges']

In [ ]:
from sklearn.model_selection import train_test_split
x_train ,x_test, y_train , y_test = train_test_split(x,y,)

In [ ]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred = lr.predict(x_test)

In [ ]:
y_pred

array([ 8666.97733585,  7817.39335602, 12067.92044043,  6798.68363652,
        4809.65972578, 28899.45098698,  3836.60721785,  6260.82257896,
        8966.82631642, 30268.62218284,  2028.1143744 ,  9280.22236533,
       11173.3343946 ,  9836.83213787,  3157.67044604, 17530.14974794,
        7160.70375657,  5267.19616705,  7494.73249834,  9252.03190795,
        6770.31194716, 12518.51777158, 36431.59367869, 17487.44473493,
       33491.72018715,  8379.60130156,  8473.19272432,  3533.90461902,
        3050.49245754,  6008.096116  ,  2340.28147044,  7500.02364724,
       10975.11236364,  7000.64550949,  5637.10054094,  5973.28570896,
       29331.38894996,  2760.8661997 ,  6551.55103449,  7474.94018723,
       34688.81343093,  9672.76219921,  9395.07980703, 13494.36468366,
       10751.54095648,  9285.54949941,  1708.61816327, 14051.6880616 ,
       29157.66385784, 34128.3346294 , 15649.54523014, 33398.98904712,
       13656.55561476,  4613.5642077 ,  7125.74954725,  3035.11110833,
       31667.02454013, 38755.48969786, 13003.57198543, 33321.42649295,
       10569.36548576,  1249.12596109, 14321.5022703 ,   113.25807921,
       12438.67299904, 11969.88716881,  9907.85644168,  2335.3500734 ,
       39978.58210291,   800.36797717,  5258.24699279,  8972.59011865,
       38477.14676777, 16811.0696891 ,  8556.13098371, 26775.68481492,
       10918.76360663,  3485.75719488, 26184.39044878,  9065.00833626,
       10764.57111242,  5176.72943332, 11196.39437585,  2154.25528879,
       11597.85295409,  6277.42555953,  6448.63844589,  3008.81797655,
       12910.71089666,  5913.46477533, 12184.62678152, 11940.98452923,
       30466.73033542,  6351.34347097, 38530.07080398,  1298.03701361,
        7013.31451489,  8608.628853  , 11204.97409382,  1670.61204592,
       17337.41713433,  8570.20726057, 10863.41146085, 16717.01565716,
        8341.46126313, 34444.6336857 , 10158.96713301,  5652.99262089,
        5595.33161494,   512.59906288,  -328.90623581, 24234.71977419,
        8497.78186699,  4896.2058426 ,  3474.97391654, 11736.51966294,
        3587.52045169,  5099.72061923,  9404.14316433,  9974.99004196,
        8815.25873465, 14831.66986807, 12296.9879494 ,  2406.6587957 ,
        3987.20606592, 10621.0492679 , 12530.59735641, 11326.500361  ,
       27858.63232827,  4481.39957978, 28979.30708524,  3775.41370584,
        5419.18335918,  5002.08704316, 31687.87125658,  5622.82964948,
         571.51002732, 29074.44116942, 12255.06139192, 15728.3956221 ,
       30792.34085315, 10111.82922128, 11343.49796329, 30046.50535802,
       38055.22178414,  8398.21515692, 28214.19860936, 11752.39662159,
        7786.06721309,  7832.91914139,  4598.18174316, 33785.75676249,
        3050.49245754,  6260.2035635 ,  5137.73595956,  5561.0988213 ,
        1084.2621304 ,  4431.58747636, 17849.45421202, 29506.0200144 ,
        4410.93552692, 11970.43850147, 36286.42499881,  7219.50053797,
       11714.25688783, 15139.47937437, 38135.45943669, 14171.578033  ,
        7509.01932174, 11575.60418495, 18587.38174292, 29510.63083098,
        6858.66874435, 10200.06132035,  9432.40067065, 37617.00419   ,
        8093.73785237, 11090.85237846,  3309.72516856,  5053.57226271,
        4210.48015341,  9531.99763382,  7626.13017322, 10002.00572927,
        8237.05760102,  8336.63482616,  5775.4485953 , 33839.79349762,
       11458.72437981, 12148.09471173, 13565.17400095,  -836.49013892,
        9913.28660986, 40032.05858709,  2185.95263719,  8639.82568107,
       36201.36646459, 10480.49571668, 35381.86837362,  3705.72075515,
        7721.1406746 ,  9242.59909437, 14861.95594082, 26682.11903906,
       13033.70961463, 15474.60359434,  9045.30887339, 12458.10602922,
       12908.9723529 ,  8163.23332394, 11615.56606322, 14744.19787464,
       37285.08490332, 16110.96993245,  4767.92331857, 37190.78307193,
       12862.72111453, 26987.35979521,  8553.4603253 ,  6723.89062574,
        3396.836624  , 11401.16164949,  6192.18976568, 14441.42249481,
       10917.08271206,  4747.43076033,  8909.38587679, 12381.47653877,
         955.7204812 ,  7289.43986812,  6827.14977089, 12085.58704932,
       12247.56826889, 28581.6478068 , 13117.55943999,  5404.77821744,
        9370.19144323, 34556.7934021 , 41299.3846606 , 33782.53209117,
       25727.38400535, 11897.80337199,  9600.13483766, 23950.47191983,
        3410.20184782, 27183.60089982, 11631.07211056, 13264.69198843,
       13344.04039725, 30142.32520191, 33993.17098416,  5257.56173906,
       15543.43005931,  5747.23361688,  7519.38390694, 34715.43494614,
        8460.44126534, 11473.04210072, 27015.06247797, 18683.51813855,
       11760.63598603,  5451.74384734,  5771.0444808 , 31117.71248972,
        8744.85775837, 14650.11563597, 17584.25272136,  2221.41565128,
       28899.39381925, 33634.71155237, 15050.60960529, 14334.11389935,
       10193.3381598 , 11711.24526653, 13033.03518063,  9010.6738    ,
        7598.06089121,  7162.87452852, 10972.49250702, 12984.48978882,
        5827.65393844,  8682.14020765, 10392.89519451,  8662.79619509,
        3296.87926457, 15226.59591749,  8821.6316955 , 13196.1647691 ,
        2627.9105548 ,  8016.13564535, 11346.81310726,  5759.09454003,
       36804.78820791, 29091.98612148,  4865.02034025, 16690.26992529,
       24298.00028796, 12432.93530078, 10501.55551499, 11557.59532108,
        7969.0201519 ,  6207.30007598, 16652.44805989, 10050.15507938,
       11433.4499834 , 11082.93787151, 16286.74825047, 10555.49892044,
       15956.0816589 ,  2060.28834849, 10134.68792783, 10205.90268658,
       27077.79165908, 29104.4468035 , 10731.85533332, 13293.95613959,
       35691.44474031,  6702.80806942, 10697.60517722, 27520.53755986,
       13644.68498719, 13153.48699976,  3084.61329877, 31591.53308029,
       37832.22476179,  8840.65816889,  8159.79571249, 10071.04286868,
        9037.22283888, 29088.35805508, 11777.06776823, 31414.23581125,
        5887.7229762 , 14259.55485884,  4803.7683684 ])

In [ ]:
y_test

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_score(y_test, y_pred)

0.7228459126030786

In [ ]:
tip =  pd.read_csv('/content/tips - tips.csv')
tip.head(2)

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lb = LabelEncoder()

In [ ]:
tip['day'] = lb.fit_transform(tip['day'])
tip['sex'] = lb.fit_transform(tip['sex'])
tip['smoker'] = lb.fit_transform(tip['smoker'])
tip['time'] = lb.fit_transform(tip['time'])

In [ ]:
tip

     total_bill   tip  sex  smoker  day  time  size
0         16.99  1.01    0       0    2     0     2
1         10.34  1.66    1       0    2     0     3
2         21.01  3.50    1       0    2     0     3
3         23.68  3.31    1       0    2     0     2
4         24.59  3.61    0       0    2     0     4
..          ...   ...  ...     ...  ...   ...   ...
239       29.03  5.92    1       0    1     0     3
240       27.18  2.00    0       1    1     0     2
241       22.67  2.00    1       1    1     0     2
242       17.82  1.75    1       0    1     0     2
243       18.78  3.00    0       0    3     0     2

[244 rows x 7 columns]